name: build
description: Builds odata-lib

inputs:
  appDir:
    dir:
      default: .
  github:
    object:
      constraints:
        properties:
          accessToken:
            minLength: 1
            type: string
            writeOnly: true
          username:
            minLength: 1
            type: string
        required: [accessToken, username]
      description: Creds for GitHub.
  HOME:
    dir:
      description: Home directory of caller; used to access aws config

run:
  container:
    image: { ref: "maven:3.8.6-amazoncorretto-18" }
    cmd: [mvn, deploy]
    dirs:
      /src: $(appDir)
      /root/.aws: $(HOME/.aws)
      /root/.m2: $(HOME/.m2)
    workDir: /src
